print("aksjdnaksdjnad")
print("akjfndsalksda")
print("kejfndsflsdfmsdfs dfsdf")
print("aksjdnaksdjnad")
print("akjfndsalksda")
print("kejfndsflsdfmsdfs dfsdf")
print("aksjdnaksdjnad")
print("akjfndsalksda")
print("kejfndsflsdfmsdfs dfsdf")
print("aksjdnaksdjnad")
print("akjfndsalksda")
print("kejfndsflsdfmsdfs dfsdf")